### ISSUE TITLE
Non working links from ZeroUp search

### ISSUE THREAD

**Issue by slrslr** [krixano/NewImportantZites#3]
Hi,

when i go to http://127.0.0.1:43110/1MiS3ud9JogSQpd1QVmM6ETHRmk5RgJn6E/?/zite/zeroup

and hover some result, i see hyperlinks ends with a code:

example URL:
http://127.0.0.1:43110/1MiS3ud9JogSQpd1QVmM6ETHRmk5RgJn6E/function%20n(n)%7Bvar%20r=arguments.length;return%20r?r%3E1?t.apply(e,arguments):t.call(e,n):t.call(e)}

**Comment by krixano** [comment]
Okay, thanks. Will fix later

**Comment by krixano** [comment]
This has been fixed with the latest update (which I have just pushed out)!
